// src/main/resources/application.yaml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gradience
    username: <YOUR_DB_USERNAME>
    password: <YOUR_DB_PASSWORD>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update        # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
